language: python
python: 
  - "2.7"
  - "3.4" 
virtualenv:
  system_site_packages: true  
# command to install dependencies
install:
  - apt install python-pytest
# command to run tests
script:
  - pytest


